testbed:
  name: "CONFIGconfig.yaml"

devices:
  IOU1:
    type: router
    os: ios
    custom:
      hostname: IOU1

      dhcp_pools:
        guests:
          network: 192.168.101.0/24
          default_router: 192.168.101.1
          dns_server: 192.168.10.10
          domain_name: savnet.hu
          excluded_address_ranges:
            - {start: 192.168.101.1, end: 192.168.101.99}
            - {start: 192.168.101.201, end: 192.168.101.254}

      routes:
        to_server:
          to_ip: 192.168.10.0/24
          via: 192.168.11.254

    connections:
      ssh: # numele conexiunii, orice
        class: ssh_connector.SSHConnector
        protocol: ssh
        ip: 192.168.11.1
        port: 22
        credentials:
          default: # numele credentialului, orice
            username: user
            password: pass
      telnet:
        class: telnet_connector.TelnetConnector
        protocol: telnet
        ip: 192.168.0.100
        port: 5012
  CSR:
    type: router
    os: iosxe
    platform: csr1000v
    custom:
      hostname: CSR
      routes:
        to_server_network:
          to_ip: 192.168.11.0/24
          via: 192.168.102.1
    connections:
      telnet:
        class: telnet_connector.TelnetConnector
        protocol: telnet
        ip: 192.168.0.100
        port: 5038
      ssh:
        class: ssh_connector.SSHConnector
        protocol: ssh
        ip: 192.168.102.2
        port: 22
        credentials:
          default:
            username: user
            password: pass

  UbuntuServer:
    type: server_pc
    os: ubuntu

    custom:
      routes:
        to_guest_network:
          to_ip: 192.168.101.0/24
          via: 192.168.11.1
        to_csr_network:
          to_ip: 192.168.102.0/24
          via: 192.168.11.1

    credentials:
      login:
        username: osboxes
        password: osboxes.org
    connections:
      telnet:
        class: telnet_connector.TelnetConnector
        protocol: telnet
        ip: 192.168.0.100
        port: 5903

  UbuntuGuest1:
    type: guest_pc
    os: ubuntu
    connections:
      telnet:
        class: telnet_connector.TelnetConnector
        protocol: telnet
        ip: 192.168.0.100
        port: 5058

topology:
  IOU1:
    interfaces:
      Ethernet0/0:
        alias: initial
        type: ethernet # nu e valoare fixa, e folosita sa grupezi interfete
        link: "to ubuntu" # asta e un nume descriptiv
        ipv4: 192.168.11.1/24
      Ethernet0/1:
        type: ethernet
        link: "to guest"
        ipv4: 192.168.101.1/24
      Ethernet0/2:
        type: ethernet
        link: "to csr"
        ipv4: 192.168.102.1/24
      Ethernet0/3:
        type: ethernet
        link: ""
        ipv4: 192.168.103.1/24
      Ethernet1/0:
        type: ethernet
        link: ""
        ipv4: 192.168.104.1/24
  CSR:
    interfaces:
      GigabitEthernet1:
        alias: initial
        type: gigabit_ethernet
        link: "to IOU1"
        ipv4: 192.168.102.2/24

  UbuntuServer:
    interfaces:
      eth1:
        type: ethernet
        link: "to IOU1"
        ipv4: 192.168.11.254/24

  UbuntuGuest1:
    interfaces:
      eth0:
        type: ethernet
        link: "to IOU1"